### ISSUE TITLE
screen.h no such file or directory

### ISSUE THREAD

**Issue by mark-orion** [HeadphoneCairn/Roudi#1]
Great project. Just trying it out but found a little bug:
The include statement is #include "screen.h", but should be #include "Screen.h". Otherwise it won't compile (on Linux).

**Comment by HeadphoneCairn** [comment]
Hi Mark,

Thanks for finding this bug. As you might have expected, I am working under
Windows, which doesn't care about the case of the file names.
I'll make an update and push it one of the next days.

regards,

**Comment by HeadphoneCairn** [comment]
Fixed in v1.2.0.
